from types import SimpleNamespace

import jax
import numpy
import pytest

from pyscfad import df, gto
from pyscfad import numpy as np
from pyscfad.lno import lno_base


def _water_mol():
    mol = gto.Mole(
        atom="O 0 0 0; H 0 0 1; H 0 1 0",
        basis="sto-3g",
        verbose=0,
        max_memory=200,
    )
    mol.build(trace_exp=False, trace_ctr_coeff=False)
    return mol


def _df_holder(mol):
    with_df = df.DF(mol, auxbasis="weigend", incore=True)
    with_df.max_memory = mol.max_memory
    return SimpleNamespace(mol=mol, with_df=with_df)


def _local_coeff(mol, atmlst):
    ao_idx = lno_base.dlno_util.ao_index_by_atom(mol, atmlst)
    rng = numpy.random.default_rng(14)
    return np.asarray(rng.normal(size=(ao_idx.size, 5)))


def _lov_norm(mol, coeff, atmlst, integral_direct):
    lov = lno_base.get_local_Lov(
        _df_holder(mol),
        coeff,
        2,
        atmlst,
        integral_direct=integral_direct,
    )
    return np.einsum("Lia,Lia->", lov, lov)


def test_integral_direct_local_lov_matches_cderi_without_building_local_df(
    monkeypatch,
):
    mol = _water_mol()
    atmlst = numpy.asarray([0, 1], dtype=numpy.int32)
    coeff = _local_coeff(mol, atmlst)
    reference = lno_base.get_local_Lov(
        _df_holder(mol), coeff, 2, atmlst
    )

    def forbidden_local_df(*args, **kwargs):
        raise AssertionError("integral-direct Lov must not build an AO-pair CDERI")

    monkeypatch.setattr(lno_base, "get_local_df", forbidden_local_df)
    direct = lno_base.get_local_Lov(
        _df_holder(mol), coeff, 2, atmlst, integral_direct=True
    )

    numpy.testing.assert_allclose(
        numpy.asarray(direct), numpy.asarray(reference), atol=1e-11, rtol=1e-11
    )


def test_integral_direct_local_lov_preserves_coeff_and_coordinate_vjps():
    mol = _water_mol()
    atmlst = numpy.asarray([0, 1], dtype=numpy.int32)
    coeff = _local_coeff(mol, atmlst)

    value_ref, coeff_bar_ref = jax.value_and_grad(
        lambda coeff_: _lov_norm(mol, coeff_, atmlst, False)
    )(coeff)
    value_direct, coeff_bar_direct = jax.value_and_grad(
        lambda coeff_: _lov_norm(mol, coeff_, atmlst, True)
    )(coeff)
    numpy.testing.assert_allclose(value_direct, value_ref, atol=1e-11, rtol=1e-11)
    numpy.testing.assert_allclose(
        numpy.asarray(coeff_bar_direct),
        numpy.asarray(coeff_bar_ref),
        atol=1e-10,
        rtol=1e-10,
    )

    _, mol_bar_ref = jax.value_and_grad(
        lambda mol_: _lov_norm(mol_, coeff, atmlst, False)
    )(mol)
    _, mol_bar_direct = jax.value_and_grad(
        lambda mol_: _lov_norm(mol_, coeff, atmlst, True)
    )(mol)
    numpy.testing.assert_allclose(
        numpy.asarray(mol_bar_direct.coords),
        numpy.asarray(mol_bar_ref.coords),
        atol=1e-9,
        rtol=1e-9,
    )


@pytest.mark.parametrize(
    ("configured_mb", "expected_mb"),
    ((None, 256.0), (7.0, 7.0)),
)
def test_integral_direct_coordinate_vjp_uses_forward_block_budget(
    monkeypatch, configured_mb, expected_mb
):
    mol = _water_mol()
    atmlst = numpy.asarray([0, 1], dtype=numpy.int32)
    coeff = _local_coeff(mol, atmlst)
    if configured_mb is None:
        monkeypatch.delenv(
            "PYSCFAD_LNO_LOCAL_DIRECT_INT3C_BLOCK_MB", raising=False
        )
    else:
        monkeypatch.setenv(
            "PYSCFAD_LNO_LOCAL_DIRECT_INT3C_BLOCK_MB",
            str(configured_mb),
        )

    real_vjp = lno_base._cderi_vjp._int3c_mo_deriv_coords_vjp
    seen = []

    def checked_vjp(*args, **kwargs):
        seen.append(kwargs.get("block_memory_mb"))
        return real_vjp(*args, **kwargs)

    monkeypatch.setattr(
        lno_base._cderi_vjp,
        "_int3c_mo_deriv_coords_vjp",
        checked_vjp,
    )
    jax.value_and_grad(
        lambda mol_: _lov_norm(mol_, coeff, atmlst, True)
    )(mol)
    assert seen == [expected_mb]


def test_integral_direct_local_lov_general_cotangent_matches_coordinate_fd():
    """Exercise the nonsymmetric Lov cotangent generated by fragment MP2."""
    mol = _water_mol()
    atmlst = numpy.asarray([0, 1], dtype=numpy.int32)
    coeff = _local_coeff(mol, atmlst)
    reference = lno_base.get_local_Lov(
        _df_holder(mol), coeff, 2, atmlst, integral_direct=True
    )
    rng = numpy.random.default_rng(91)
    cotangent = np.asarray(rng.normal(size=reference.shape))

    def objective(mol_):
        lov = lno_base.get_local_Lov(
            _df_holder(mol_), coeff, 2, atmlst, integral_direct=True
        )
        return np.einsum("Lia,Lia->", cotangent, lov)

    _, mol_bar = jax.value_and_grad(objective)(mol)
    analytic = float(numpy.asarray(mol_bar.coords)[1, 2])
    coords = numpy.asarray(mol.atom_coords())
    symbols = [mol.atom_symbol(atom) for atom in range(mol.natm)]

    def displaced_value(delta):
        displaced_coords = coords.copy()
        displaced_coords[1, 2] += delta
        displaced = gto.Mole(
            atom=list(zip(symbols, displaced_coords)),
            unit="Bohr",
            basis="sto-3g",
            verbose=0,
            max_memory=200,
        )
        displaced.build(trace_exp=False, trace_ctr_coeff=False)
        return float(objective(displaced))

    step = 2e-4
    finite_difference = (
        displaced_value(-2 * step)
        - 8 * displaced_value(-step)
        + 8 * displaced_value(step)
        - displaced_value(2 * step)
    ) / (12 * step)
    numpy.testing.assert_allclose(
        analytic, finite_difference, atol=2e-8, rtol=2e-8
    )
