from pathlib import Path
from types import SimpleNamespace

import h5py
import jax
import numpy
import pytest
from pyscf import lib as pyscf_lib
from pyscf.mp import dfmp2

from pyscfad import df, gto
from pyscfad import numpy as np
from pyscfad.lno import lno_base


def _water_mol():
    mol = gto.Mole(
        atom="O 0 0 0; H 0 0 1; H 0 1 0",
        basis="sto-3g",
        verbose=0,
        max_memory=200,
    )
    mol.build(trace_exp=False, trace_ctr_coeff=False)
    return mol


def _df_holder(mol):
    with_df = df.DF(mol, auxbasis="weigend", incore=True)
    with_df.max_memory = mol.max_memory
    return SimpleNamespace(mol=mol, with_df=with_df)


def _local_coeff(mol, atmlst):
    ao_idx = lno_base.dlno_util.ao_index_by_atom(mol, atmlst)
    rng = numpy.random.default_rng(14)
    return np.asarray(rng.normal(size=(ao_idx.size, 5)))


def _lov_norm(mol, coeff, atmlst, integral_direct):
    lov = lno_base.get_local_Lov(
        _df_holder(mol),
        coeff,
        2,
        atmlst,
        integral_direct=integral_direct,
    )
    return np.einsum("Lia,Lia->", lov, lov)


def test_integral_direct_local_lov_matches_cderi_without_building_local_df(
    monkeypatch,
):
    mol = _water_mol()
    atmlst = numpy.asarray([0, 1], dtype=numpy.int32)
    coeff = _local_coeff(mol, atmlst)
    reference = lno_base.get_local_Lov(
        _df_holder(mol), coeff, 2, atmlst
    )

    def forbidden_local_df(*args, **kwargs):
        raise AssertionError("integral-direct Lov must not build an AO-pair CDERI")

    monkeypatch.setattr(lno_base, "get_local_df", forbidden_local_df)
    direct = lno_base.get_local_Lov(
        _df_holder(mol), coeff, 2, atmlst, integral_direct=True
    )

    numpy.testing.assert_allclose(
        numpy.asarray(direct), numpy.asarray(reference), atol=1e-11, rtol=1e-11
    )


def test_integral_direct_local_lov_preserves_coeff_and_coordinate_vjps():
    mol = _water_mol()
    atmlst = numpy.asarray([0, 1], dtype=numpy.int32)
    coeff = _local_coeff(mol, atmlst)

    value_ref, coeff_bar_ref = jax.value_and_grad(
        lambda coeff_: _lov_norm(mol, coeff_, atmlst, False)
    )(coeff)
    value_direct, coeff_bar_direct = jax.value_and_grad(
        lambda coeff_: _lov_norm(mol, coeff_, atmlst, True)
    )(coeff)
    numpy.testing.assert_allclose(value_direct, value_ref, atol=1e-11, rtol=1e-11)
    numpy.testing.assert_allclose(
        numpy.asarray(coeff_bar_direct),
        numpy.asarray(coeff_bar_ref),
        atol=1e-10,
        rtol=1e-10,
    )

    _, mol_bar_ref = jax.value_and_grad(
        lambda mol_: _lov_norm(mol_, coeff, atmlst, False)
    )(mol)
    _, mol_bar_direct = jax.value_and_grad(
        lambda mol_: _lov_norm(mol_, coeff, atmlst, True)
    )(mol)
    numpy.testing.assert_allclose(
        numpy.asarray(mol_bar_direct.coords),
        numpy.asarray(mol_bar_ref.coords),
        atol=1e-9,
        rtol=1e-9,
    )


@pytest.mark.parametrize(
    ("configured_mb", "expected_mb"),
    ((None, 256.0), (7.0, 7.0)),
)
def test_integral_direct_coordinate_vjp_uses_forward_block_budget(
    monkeypatch, configured_mb, expected_mb
):
    mol = _water_mol()
    atmlst = numpy.asarray([0, 1], dtype=numpy.int32)
    coeff = _local_coeff(mol, atmlst)
    if configured_mb is None:
        monkeypatch.delenv(
            "PYSCFAD_LNO_LOCAL_DIRECT_INT3C_BLOCK_MB", raising=False
        )
    else:
        monkeypatch.setenv(
            "PYSCFAD_LNO_LOCAL_DIRECT_INT3C_BLOCK_MB",
            str(configured_mb),
        )

    real_vjp = lno_base._cderi_vjp._int3c_mo_deriv_coords_vjp
    seen = []

    def checked_vjp(*args, **kwargs):
        seen.append(kwargs.get("block_memory_mb"))
        return real_vjp(*args, **kwargs)

    monkeypatch.setattr(
        lno_base._cderi_vjp,
        "_int3c_mo_deriv_coords_vjp",
        checked_vjp,
    )
    jax.value_and_grad(
        lambda mol_: _lov_norm(mol_, coeff, atmlst, True)
    )(mol)
    assert seen == [expected_mb]


def test_integral_direct_local_lov_general_cotangent_matches_coordinate_fd():
    """Exercise the nonsymmetric Lov cotangent generated by fragment MP2."""
    mol = _water_mol()
    atmlst = numpy.asarray([0, 1], dtype=numpy.int32)
    coeff = _local_coeff(mol, atmlst)
    reference = lno_base.get_local_Lov(
        _df_holder(mol), coeff, 2, atmlst, integral_direct=True
    )
    rng = numpy.random.default_rng(91)
    cotangent = np.asarray(rng.normal(size=reference.shape))

    def objective(mol_):
        lov = lno_base.get_local_Lov(
            _df_holder(mol_), coeff, 2, atmlst, integral_direct=True
        )
        return np.einsum("Lia,Lia->", cotangent, lov)

    _, mol_bar = jax.value_and_grad(objective)(mol)
    analytic = float(numpy.asarray(mol_bar.coords)[1, 2])
    coords = numpy.asarray(mol.atom_coords())
    symbols = [mol.atom_symbol(atom) for atom in range(mol.natm)]

    def displaced_value(delta):
        displaced_coords = coords.copy()
        displaced_coords[1, 2] += delta
        displaced = gto.Mole(
            atom=list(zip(symbols, displaced_coords)),
            unit="Bohr",
            basis="sto-3g",
            verbose=0,
            max_memory=200,
        )
        displaced.build(trace_exp=False, trace_ctr_coeff=False)
        return float(objective(displaced))

    step = 2e-4
    finite_difference = (
        displaced_value(-2 * step)
        - 8 * displaced_value(-step)
        + 8 * displaced_value(step)
        - displaced_value(2 * step)
    ) / (12 * step)
    numpy.testing.assert_allclose(
        analytic, finite_difference, atol=2e-8, rtol=2e-8
    )


def test_build_local_lov_h5_matches_integral_direct_pair_major(tmp_path):
    mol = _water_mol()
    atmlst = numpy.asarray([0, 1], dtype=numpy.int32)
    coeff = _local_coeff(mol, atmlst)
    nocc = 2
    reference = lno_base.get_local_Lov(
        _df_holder(mol), coeff, nocc, atmlst, integral_direct=True
    )
    path = tmp_path / "local-lov.h5"

    info = lno_base.build_local_Lov_h5(
        _df_holder(mol), coeff, nocc, atmlst, path
    )

    reference_array = numpy.asarray(reference)
    naux = reference_array.shape[0]
    nvir = reference_array.shape[2]
    assert info == lno_base.LocalLovH5Info(
        path=str(path),
        naux=naux,
        nocc=nocc,
        nvir=nvir,
        dtype=str(reference_array.dtype),
    )
    with h5py.File(path, "r") as h5file:
        assert set(h5file) == {"lov"}
        assert h5file["lov"].shape == (nocc * nvir, naux)
        assert h5file["lov"].dtype == numpy.dtype(reference_array.dtype)
        assert h5file["lov"].chunks is None
        assert h5file["lov"].compression is None
        numpy.testing.assert_allclose(
            h5file["lov"][:],
            reference_array.reshape(naux, -1).T,
            rtol=2e-11,
            atol=2e-12,
        )


def test_build_local_lov_h5_rejects_insufficient_scratch_space(
    monkeypatch, tmp_path
):
    mol = _water_mol()
    atmlst = numpy.asarray([0, 1], dtype=numpy.int32)
    coeff = _local_coeff(mol, atmlst)
    nocc = 2
    nvir = coeff.shape[1] - nocc
    fake_mol = lno_base.make_local_mol(mol, atmlst)
    auxmol = lno_base.df_addons.make_auxmol(
        fake_mol, _df_holder(mol).with_df.auxbasis
    )
    required = int(3.25 * auxmol.nao * nocc * nvir * 8) + 1024**3
    path = tmp_path / "too-large.h5"
    monkeypatch.setattr(
        lno_base.shutil,
        "disk_usage",
        lambda unused: SimpleNamespace(free=required - 1),
    )

    with pytest.raises(OSError) as excinfo:
        lno_base.build_local_Lov_h5(
            _df_holder(mol), coeff, nocc, atmlst, path
        )

    message = str(excinfo.value)
    assert str(path) in message
    assert f"free bytes={required - 1}" in message
    assert f"required bytes={required}" in message
    assert not path.exists()


def test_build_local_lov_h5_uses_configured_tmpdir_and_removes_raw_store(
    monkeypatch, tmp_path
):
    mol = _water_mol()
    atmlst = numpy.asarray([0, 1], dtype=numpy.int32)
    coeff = _local_coeff(mol, atmlst)
    scratch = tmp_path / "scratch"
    scratch.mkdir()
    raw_paths = []
    real_h5tmp = pyscf_lib.H5TmpFile

    def tracked_h5tmp(*args, **kwargs):
        raw_file = real_h5tmp(*args, **kwargs)
        raw_paths.append(Path(raw_file.filename))
        return raw_file

    monkeypatch.setattr(pyscf_lib.param, "TMPDIR", str(scratch))
    monkeypatch.setattr(pyscf_lib, "H5TmpFile", tracked_h5tmp)

    lno_base.build_local_Lov_h5(
        _df_holder(mol), coeff, 2, atmlst, tmp_path / "local-lov.h5"
    )

    assert raw_paths
    assert all(raw_path.parent == scratch for raw_path in raw_paths)
    assert all(not raw_path.exists() for raw_path in raw_paths)


def test_build_local_lov_h5_removes_partial_target_after_failure(
    monkeypatch, tmp_path
):
    mol = _water_mol()
    atmlst = numpy.asarray([0, 1], dtype=numpy.int32)
    coeff = _local_coeff(mol, atmlst)
    path = tmp_path / "failed.h5"

    def failing_producer(with_df, occ_coeff, vir_coeff, max_memory,
                         h5obj=None, log=None):
        del with_df, max_memory, log
        h5obj.create_dataset(
            "ovL",
            (occ_coeff.shape[1] * vir_coeff.shape[1], 4),
            dtype=numpy.float64,
            chunks=(1, 4),
        )
        raise RuntimeError("producer failed")

    monkeypatch.setattr(dfmp2, "_init_mp_df_eris_direct", failing_producer)

    with pytest.raises(RuntimeError, match="producer failed"):
        lno_base.build_local_Lov_h5(
            _df_holder(mol), coeff, 2, atmlst, path
        )

    assert not path.exists()
    assert not list(tmp_path.glob(".*failed.h5.*"))


def test_build_local_lov_h5_never_converts_complete_lov_dataset(
    monkeypatch, tmp_path
):
    mol = _water_mol()
    atmlst = numpy.asarray([0, 1], dtype=numpy.int32)
    coeff = _local_coeff(mol, atmlst)
    path = tmp_path / "local-lov.h5"
    original_array = h5py.Dataset.__array__
    original_getitem = h5py.Dataset.__getitem__
    original_setitem = h5py.Dataset.__setitem__
    lov_reads = []
    lov_write_sizes = []

    def forbidden_array(dataset, *args, **kwargs):
        if dataset.name == "/lov":
            raise AssertionError("the complete /lov dataset was converted")
        return original_array(dataset, *args, **kwargs)

    def tracked_getitem(dataset, key):
        if dataset.name == "/lov":
            lov_reads.append(key)
        return original_getitem(dataset, key)

    def tracked_setitem(dataset, key, value):
        if dataset.name == "/lov":
            row_key = key[0] if isinstance(key, tuple) else key
            selected_rows = numpy.arange(dataset.shape[0])[row_key]
            lov_write_sizes.append(selected_rows.size * dataset.shape[1])
        return original_setitem(dataset, key, value)

    monkeypatch.setattr(h5py.Dataset, "__array__", forbidden_array)
    monkeypatch.setattr(h5py.Dataset, "__getitem__", tracked_getitem)
    monkeypatch.setattr(h5py.Dataset, "__setitem__", tracked_setitem)

    info = lno_base.build_local_Lov_h5(
        _df_holder(mol), coeff, 2, atmlst, path
    )

    assert lov_reads == []
    assert lov_write_sizes
    assert max(lov_write_sizes) < 2 * (coeff.shape[1] - 2) * info.naux
